name: repo-mirror
on:
  schedule:
    - cron:  '0/5 * * * *'
  workflow_dispatch:
  pull_request:
  push:
     branches:
       - main

#permissions:
#  contents: read
#  pull-requests: read


jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Git Sync Alternate
      uses: actions/checkout@v3
 #   - run: git clone https://github.com/srinivas3000/testrepo.git
   # - run: cd testrepo/
   # - run: git remote add nrepo git@github.com:gitsrinuhub/originalrepo.git
    #- run: git fetch -p origin
   # - run: git remote -v 
   # - run: git push --mirror https://gitsrinuhub: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@github.com/gitsrinuhub/originalrepo.git
    - run: git remote update
    - run: git push --mirror https://gitsrinuhub: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@github.com/gitsrinuhub/originalrepo.git 
      
      
      
      
      
