name: repo-mirror
on:
  schedule:
    - cron:  '0/5 * * * *'
  workflow_dispatch:
  pull_request:
  push:
     branches:
       - main

#permissions:
#  contents: read
#  pull-requests: read


jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Git Sync Alternate
      uses: actions/checkout@v3
    - run: git clone --mirror https://gitsrinuhub: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@github.com/gitsrinuhub/replicarepo.git
    - run: cd replicarepo.git/
    - run: git remote set-url --push origin git@github.com:gitsrinuhub/originalrepo.git
    - run: git fetch -p origin
    - run: git remote -v 
    - run: git push --mirror git@github.com:gitsrinuhub/originalrepo.git  
      
      
      
      
      
